[build]
  functions = "functions"
[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[headers]]
 /orderItems.csv
  [headers.values]
   Content-Type = text/csv
   content-disposition: attachment; filename="orderItems.csv"
 