[build]
  functions = "functions"
[functions]
  directory = "functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

  [[headers]]
  for = "/*"
  [headers.values]
     content-type = '''
     application/json,
     application/x-www-form-urlencoded'''
